# Generated by Django 3.0 on 2019-12-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmp', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
    ]
