# Generated by Django 3.0 on 2019-12-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascensores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudempresa',
            options={'ordering': ['nombreEmp']},
        ),
        migrations.RemoveField(
            model_name='solicitudempresa',
            name='id',
        ),
        migrations.AlterField(
            model_name='solicitudempresa',
            name='nombreEmp',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
